name: Build all apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: wirepas/sdk-builder:latest

    steps:
    - uses: actions/checkout@v2
    - name: Accept license 
      run: touch .license_accepted
    - name: Create dummy key file
      run: touch custom_bootloader_keys.ini
    - name: Build all apps
      run: ./tools/sdk_builder.py --app_only
